logging:
  config: classpath:log4j2-dev.xml
arex:
  api:
    service:
      api: http://arex-web-api.fat3.tripqate.com
  mongo:
    uri: mongodb://arex:iLoveArex@10.118.1.217:37017/arex_storage_db
  storage:
    service:
      api: http://arex-storage.fat3.tripqate.com
  schedule:
    service:
      api: http://arex-schedule.fat3.tripqate.com
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@10.118.1.217:37017/
        default:
          uri: mongodb://arex:iLoveArex@10.118.1.217:37017/arex_storage_db
          database: arex_storage_db
spring:
  data:
    redis:
      sentinel:
        nodes: 10.118.1.231:26379,10.118.1.240:26379,10.118.1.241:26379
        password: foobared
        master: mymaster
      password: foobared