arex:
  api:
    service:
      api: http://arex-web-api-find.arex-namesapce:8080
  mongo:
    uri: mongodb://arex:iLoveArex@arex-mongo-lb02-d169a9174fb6091d.elb.us-west-2.amazonaws.com:27017,arex-mongo-lb01-a107b55d34895f43.elb.us-west-2.amazonaws.com:27017,arex-mongo-lb03-42fbd33c55e070c3.elb.us-west-2.amazonaws.com:27017/arex_storage_db
  storage:
    service:
      api: http://arex-storage-discovery.arex-namesapce:8080
  schedule:
    service:
      api: http://arex-schedule-discovery.arex-namesapce:8080
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@arex-mongo-lb02-d169a9174fb6091d.elb.us-west-2.amazonaws.com:27017,arex-mongo-lb01-a107b55d34895f43.elb.us-west-2.amazonaws.com:27017,arex-mongo-lb03-42fbd33c55e070c3.elb.us-west-2.amazonaws.com:27017/
        default:
          uri: mongodb://arex:iLoveArex@arex-mongo-lb02-d169a9174fb6091d.elb.us-west-2.amazonaws.com:27017,arex-mongo-lb01-a107b55d34895f43.elb.us-west-2.amazonaws.com:27017,arex-mongo-lb03-42fbd33c55e070c3.elb.us-west-2.amazonaws.com:27017/arex_storage_db
          database: arex_storage_db
spring:
  redis:
    sentinel:
      nodes:
        - redis-nlb-sentinel-1-21717d5991fbd117.elb.us-west-2.amazonaws.com:26379
        - redis-nlb-sentinel-2-12f4a4f090826b5b.elb.us-west-2.amazonaws.com:26379
        - redis-nlb-sentinel-3-5157a7ca4208d84a.elb.us-west-2.amazonaws.com:26379
      password: Arex@raD#is
      master: mymaster
    password: Arex@raD#is