logging:
  config: classpath:log4j2-dev.xml
arex:
  api:
    service:
      api: http://10.144.62.53:8090
  mongo:
    uri: mongodb://arex:password@10.144.62.53:27017/arex_storage_db
  redis:
    uri: redis://35.94.19.164:6379
  storage:
    service:
      api: http://10.144.62.53:8093
  schedule:
    service:
      api: http://10.144.62.53:8092
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@mongo-nlb-2df9ea376fed96d7.elb.us-west-2.amazonaws.com/
        default:
          uri: mongodb://arex:iLoveArex@mongo-nlb-2df9ea376fed96d7.elb.us-west-2.amazonaws.com/arex_storage_db
          database: arex_storage_db