logging:
  config: classpath:log4j2-dev.xml
arex:
  api:
    service:
      api: http://arex-web-api-find.arex-namesapce:8080
  redis:
    uri: redis://ec2-34-215-227-222.us-west-2.compute.amazonaws.com:6379/
  mongo:
    uri: mongodb://arex:iLoveArex@52.88.84.95:27017/arex_storage_db
  storage:
    service:
      api: http://arex-storage-discovery.arex-namesapce:8080
  schedule:
    service:
      api: http://arex-schedule-discovery.arex-namesapce:8080
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@52.88.84.95:27017/
        default:
          uri: mongodb://arex:iLoveArex@52.88.84.95:27017/arex_storage_db
          database: arex_storage_db