arex:
  api:
    service:
      api: http://arex-web-api-find.arex-namesapce:8080
  mongo:
    uri: mongodb://arex:password@10.144.62.53:27017/arex_storage_db
  redis:
    uri: redis://redis-inner-nlb-2203a1ba55b82a05.elb.us-west-2.amazonaws.com:6379/
  storage:
    service:
      api: http://arex-storage-discovery.arex-namesapce:8080
  schedule:
    service:
      api: http://arex-schedule-discovery.arex-namesapce:8080
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@mongo-inner-nlb-d5fc37ce9602213c.elb.us-west-2.amazonaws.com/
        default:
          uri: mongodb://arex:iLoveArex@mongo-inner-nlb-d5fc37ce9602213c.elb.us-west-2.amazonaws.com/arex_storage_db
          database: arex_storage_db