arex:
  api:
    service:
      api: http://arex-web-api-find.arex-namesapce:8080
  mongo:
    uri: mongodb://arex:iLoveArex@172.31.29.251:27017,172.31.20.184:27017,172.31.27.88:27017/arex_storage_db
  redis:
    uri: redis://redis-inner-nlb-2203a1ba55b82a05.elb.us-west-2.amazonaws.com:6379/
  storage:
    service:
      api: http://arex-storage-discovery.arex-namesapce:8080
  schedule:
    service:
      api: http://arex-schedule-discovery.arex-namesapce:8080
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@172.31.29.251:27017,172.31.20.184:27017,172.31.27.88:27017
        default:
          uri: mongodb://arex:iLoveArex@172.31.29.251:27017,172.31.20.184:27017,172.31.27.88:27017/arex_storage_db
          database: arex_storage_db