arex:
  redis:
    uri: redis://redis-inner-nlb-2203a1ba55b82a05.elb.us-west-2.amazonaws.com:6379/
  storage:
    enableDiscoveryEntryPoint: true
    recordEnv: TEST
    expirationDurationMap:
      ConfigFile: 3456000000
    defaultExpirationDuration: 345600000
    allowReRunDays: 1
  api:
    service:
      api: http://arex-web-api-find.arex-namesapce:8080
    config:
      agent:
        url: http://arex-web-api-find.arex-namesapce:8080
  agent:
    aesKey: 0EV1iPX7Zsgw22/w+XB7lPBc+bp9ac1ggnmZ49+MzBM=
#    categoryTypes:
#      - name: Hi
#        entryPoint: true
#        skipComparison: true
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@mongo-inner-nlb-d5fc37ce9602213c.elb.us-west-2.amazonaws.com/
        default:
          uri: mongodb://arex:iLoveArex@mongo-inner-nlb-d5fc37ce9602213c.elb.us-west-2.amazonaws.com/arex_storage_db
          database: arex_storage_db