logging:
  config: classpath:log4j2-dev.xml
arex:
  storage:
    cache:
      uri: redis://redis-inner-nlb-2203a1ba55b82a05.elb.us-west-2.amazonaws.com:6379/
    enableDiscoveryEntryPoint: true
    mongodbUri: mongodb://arex:password@10.144.62.53:27017/arex_storage_db
    recordEnv: TEST
    expirationDurationMap:
      ConfigFile: 3456000000
    defaultExpirationDuration: 345600000
    allowReRunDays: 1
  api:
    service:
      api: http://arex-web-api-find.arex-namesapce:8080
    config:
      agent:
        url: http://arex-web-api-find.arex-namesapce:8080
#    categoryTypes:
#      - name: Hi
#        entryPoint: true
#        skipComparison: true
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@mongo-inner-nlb-d5fc37ce9602213c.elb.us-west-2.amazonaws.com/
        default:
          uri: mongodb://arex:iLoveArex@mongo-inner-nlb-d5fc37ce9602213c.elb.us-west-2.amazonaws.com/arex_storage_db
          database: arex_storage_db