logging:
  config: classpath:log4j2-dev.xml
arex:
  redis:
    uri: redis://ec2-34-215-227-222.us-west-2.compute.amazonaws.com:6379/
  storage:
    enableDiscoveryEntryPoint: true
    recordEnv: TEST
    expirationDurationMap:
      ConfigFile: 3456000000
    defaultExpirationDuration: 345600000
    allowReRunDays: 1
  api:
    service:
      api: http://arex-web-api-find.arex-namesapce:8080
    config:
      agent:
        url: http://arex-web-api-find.arex-namesapce:8080
  agent:
    aesKey: 0EV1iPX7Zsgw22/w+XB7lPBc+bp9ac1ggnmZ49+MzBM=
#    categoryTypes:
#      - name: Hi
#        entryPoint: true
#        skipComparison: true
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@52.88.84.95:27017/
        default:
          uri: mongodb://arex:iLoveArex@52.88.84.95:27017/arex_storage_db
          database: arex_storage_db