# test
server:
  port: 8090
logging:
  config: classpath:log4j2-dev.xml
arex:
  storage:
    service:
      url: http://10.144.62.53:8093
  schedule:
    service:
      url: http://10.144.62.53:8092
  mongo:
    uri: mongodb://arex:password@10.144.62.53:27017/arex_storage_db
  redis:
    uri: redis://Redis-nlb-7f68f3434af8867b.elb.us-west-2.amazonaws.com/

saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@mongo-nlb-2df9ea376fed96d7.elb.us-west-2.amazonaws.com/
        default:
          uri: mongodb://arex:iLoveArex@mongo-nlb-2df9ea376fed96d7.elb.us-west-2.amazonaws.com/arex_storage_db
          database: arex_storage_db