# test
logging:
  config: classpath:log4j2-dev.xml
arex:
  storage:
    service:
      url: http://arex-storage.fat3.tripqate.com
  schedule:
    service:
      url: http://arex-schedule.fat3.tripqate.com
  mongo:
    uri: mongodb://arex:iLoveArex@10.118.1.217:37017/arex_storage_db

saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@10.118.1.217:37017/
        default:
          uri: mongodb://arex:iLoveArex@10.118.1.217:37017/arex_storage_db
          database: arex_storage_db
  service:
    domain: http://arex-saasservice.fat3.tripqate.com

spring:
  redis:
    host: 10.118.1.217
    port: 16379