# test
logging:
  config: classpath:log4j2-dev.xml
arex:
  storage:
    service:
      url: http://arex-storage-discovery.arex-namesapce:8080
  schedule:
    service:
      url: http://arex-schedule-discovery.arex-namesapce:8080
  redis:
    uri: redis://ec2-34-215-227-222.us-west-2.compute.amazonaws.com:6379/

saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@mongo-nlb-2df9ea376fed96d7.elb.us-west-2.amazonaws.com/
        default:
          uri: mongodb://arex:iLoveArex@mongo-nlb-2df9ea376fed96d7.elb.us-west-2.amazonaws.com/arex_storage_db
          database: arex_storage_db
