logging:
  config: classpath:log4j2-dev.xml
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@10.118.1.217:37017/
        default:
          uri: mongodb://arex:iLoveArex@10.118.1.217:37017/arex_storage_db
          database: arex_storage_db
spring:
  data:
    mongodb:
      uri: mongodb://arex:iLoveArex@10.118.1.217:37017/
      database: saas_db
  redis:
    host: 10.118.1.217
    port: 6379