server:
  port: 8080
logging:
  config: classpath:log4j2-dev.xml
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@172.31.29.251:27017,172.31.20.184:27017,172.31.27.88:27017/
        default:
          uri: mongodb://arex:iLoveArex@172.31.29.251:27017,172.31.20.184:27017,172.31.27.88:27017/arex_storage_db
          database: arex_storage_db
    systemConfig:
      comparePluginJarUrl: https://s01.oss.sonatype.org/service/local/repositories/releases/content/com/arextest/arex-compare-plugin/0.0.1/arex-compare-plugin-0.0.1.jar
spring:
  data:
    mongodb:
      uri: mongodb://root:S3cret@172.31.29.251:27017,172.31.20.184:27017,172.31.27.88:27017/
      database: saas_db
  redis:
    host: redis-inner-nlb-2203a1ba55b82a05.elb.us-west-2.amazonaws.com
    port: 6379