server:
  port: 8080
logging:
  config: classpath:log4j2-dev.xml
saas:
  tenant:
    database:
      mongo:
        uri:
          base: mongodb://arex:iLoveArex@mongo-inner-nlb-d5fc37ce9602213c.elb.us-west-2.amazonaws.com/
        default:
          uri: mongodb://arex:iLoveArex@mongo-inner-nlb-d5fc37ce9602213c.elb.us-west-2.amazonaws.com/arex_storage_db
          database: arex_storage_db
spring:
  data:
    mongodb:
      uri: mongodb://root:S3cret@mongo-inner-nlb-d5fc37ce9602213c.elb.us-west-2.amazonaws.com/
      database: saas_db
arex:
  redis:
    uri: redis://redis-inner-nlb-2203a1ba55b82a05.elb.us-west-2.amazonaws.com:6379/