arex:
  devops:
    url: http://arex-saas-devops.arex-namesapce:8080
  agent:
    aesKey: 0EV1iPX7Zsgw22/w+XB7lPBc+bp9ac1ggnmZ49+MzBM=
spring:
  data:
    mongodb:
      uri: mongodb://root:S3cret@172.31.29.251:27017,172.31.20.184:27017,172.31.27.88:27017/
      database: saas_db