FROM maven:3.9.9-eclipse-temurin-21 as builder
COPY . /usr/src/app/
WORKDIR /usr/src/app
RUN mvn clean package -pl saas-arex-api-web -am -DskipTests=true -Pjar

FROM eclipse-temurin:21-jre
COPY --from=builder /usr/src/app/saas-end-jar/web-api.jar web-api.jar
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /web-api.jar"]
